### ISSUE TITLE
Review ecl deprecation warnings

### ISSUE THREAD

**Issue by markusdregi** [equinor/libecl#679]
The deprecation warning given when importing `ert.ecl` or `ecl.ecl` refers to `res`. This should be `ecl` instead.

```
Python 3.6.9 (default, Oct 18 2019, 14:13:27)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-23)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ecl.ecl
/prog/res/komodo/bleeding3.6/root/lib/python3.6/site-packages/ert/__init__.py:6: DeprecationWarning: Importing from ert is deprecated and will be removed in a future release, use: 'from res import' instead
  DeprecationWarning
```

Note that you need to compile ecl with `-DINSTALL_ERT_LEGACY=1`.

**Comment by jondequinor** [comment]
```
>>> import ecl.ecl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ecl.ecl'
>>> import ecl
>>> ecl.__file__
'/data/usr/lib/python3.6/site-packages/ecl/__init__.py'
>>> import ert.ecl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ert'
```

:man_shrugging: ?

**Comment by jondequinor** [comment]
```
Python 3.6.8 (default, Jun 11 2019, 15:15:01) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ecl.ecl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ecl.ecl'
>>> import ert.ecl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ert'
>>> import ecl
>>> ecl.__file__
'/data/usr/lib/python3.6/site-packages/ecl/__init__.py'
>>> import res
>>> res.__file__
'/data/usr/lib/python3.6/site-packages/res/__init__.py'
>>> import ert
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ert'
```

**Comment by jondequinor** [comment]
```
>>> import ert.ecl
>>> import ecl.ecl
>>> 
```
:man_shrugging:
